# Generated by Django 4.2.5 on 2023-09-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Micdejun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('ingredients', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
