# Generated by Django 4.2.5 on 2023-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micdejun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micdejun',
            old_name='description',
            new_name='small_description',
        ),
        migrations.AddField(
            model_name='micdejun',
            name='mod_preparare',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
